### PR TITLE
Remove replication section

### PR DESCRIPTION
**Pull request by pchaussalet**

### CODE REVIEW

**Comment by Fzzr** [comment]
The remaining things to be done:
- Remove unused `replication` icon
- Remove unused ReplicationService
- Remove user-interface-descriptor for replication link
  - Rebuild montage-data cache with replication link removed

That last sub-bullet is currently preventing me from proceeding; I'm experiencing a bug that prevents any attempt to update the montage-data cache.

**Comment by pchaussalet** [comment]
@Fzzr: The changes on model generation have been rebased, it is ready for review.

**Comment by Fzzr** [comment]
@pchaussalet please re-review, but I believe that's everything I can remove here. There are also replication-related things in Calendar that I didn't touch.

**Comment by pchaussalet** [comment]
LGTM

**Comment by Fzzr** [comment]
Turned out I mis-tested the ReplicationOptions thing. I believe the change is correct, but it turns out that `Model` isn't defined in that file, so it just traces back anyway. The issue is in `replication-args.js`. Since that's a Calendar-related file, I'm hesitant to touch it here. Please advise.

**Pull request merged**
