### PR TITLE
Save config and Factory restore

### PR DESCRIPTION
**Pull request by mactanxin**
ticket: #18565 2/3 buttons

### CODE REVIEW

**Comment by pchaussalet** [comment]
- [x] Download config
- [x] Factory restore
- [x] Upload config

**Comment by mactanxin** [comment]
the Download config works the same way as download debug file. it only returns an address, which requires a *real* machine to test

**Comment by mactanxin** [comment]
I need some help, style is not working

**Comment by mactanxin** [comment]
joshuarule helped me checking this. works with the latest version of blue-shark

**Comment by mactanxin** [comment]
I tested this with suraj.

**Review by pchaussalet — APPROVED** [review]
LGTM

**Pull request merged**
