### PR TITLE
Updated: montage-data cache to 201609131929

### PR DESCRIPTION
**Pull request by mactanxin**
some changes happened to Peer model, that might affect the gui, please check

### CODE REVIEW

**Comment by mactanxin** [comment]
I found a bug in this one. Please don't merge

**Comment by mactanxin** [comment]
nvm, but the peer thing may be an issue @thibaultzanini

**Comment by pchaussalet** [comment]
Indeed, the peer change are an issue, it will break the peer interface...
One need to move `peer.address` to `peer.credentials.address` (check the exact properties names) before merging this.

**Comment by Fzzr** [comment]
@pchaussalet Please review once more

**Review by pchaussalet — APPROVED** [review]
LGTM

**Pull request merged**
